#!/bin/sh

branch="$(git rev-parse --abbrev-ref HEAD)"

if [[ "$branch" = "master" || "$branch" = "development" ]]; then
  echo "You can't commit directly to master or development branch"
  exit 1
fi
